### PR TITLE
Submission and bugfixing

### PR DESCRIPTION
**Pull request by FlorianPommerening**
That is strange, I thought I already created a pull request but now I don't see it anymore. I'll re-create it, apologies if you get it twice.

I want to move some parts on the website around (out of "registration" into "planner submission") and add some things about what we discussed on Monday. I also added a demo submission. That repo is still private. I wanted you to have a look at the changes first. One open point is about the PDDL support labels.

### CODE REVIEW

**Comment by danfis** [comment]
Looks good. I fixed couple typos and added the description of pddl features. Please, take a look and let me know if it makes sense to you. I'll also modify the demo submission to follow the rules laid out here and let you know.

**Comment by danfis** [comment]
I changed the description so that we will consider code only in the 'ipc2023-classical' branch.

Also, I created a branch ipc2023-classical in the demo submission repo, added one more apptainer recipe, changed labels according to our description, and fixed an issue with variables. Please, take a look there too. Especially, check the Supports* labels. Maybe we should also change one label to "partially, ..." so that it is clear how to write those.

**Comment by FlorianPommerening** [comment]
The changes look fine to me. The ones in the demo submission as well. It makes sense to have one label "partial" to show how this works. I would also delete the main branch, so this doesn't lead to confusion: if you navigate to the repo on Github, it will show the main branch and it also has an Apptainer file.  For the name, I would change `demo-AstarLMCut` to `demo A* with LM-cut` to show that you can use characters here that are not allowed in the shortname.

I think this is ready to make public then, right? The timeline is still missing but we can add that later. Maybe one thing to figure out is how we want to build with Github actions as Jendrik suggested. If that means authors have to include a `.github` file or something, we should include it in the instructions.

**Comment by danfis** [comment]
Mon, Jan 23, 2023 at 01:46:42PM CET, ***@***.***:
> The changes look fine to me. The ones in the demo submission as well. It makes sense to have one label "partial" to show how this works. I would also delete the main branch, so this doesn't lead to confusion: if you navigate to the repo on Github, it will show the main branch and it also has an Apptainer file.  For the name, I would change `demo-AstarLMCut` to `demo A* with LM-cut` to show that you can use characters here that are not allowed in the shortname.
Done, done and done.

> 
> I think this is ready to make public then, right? The timeline is still missing but we can add that later. Maybe one thing to figure out is how we want to build with Github actions as Jendrik suggested. If that means authors have to include a `.github` file or something, we should include it in the instructions.
Regarding github actions, it seems to me it is unnecessarily complicated
(do we have enough minutes and so on) and untested (can we run apptainer
inside docker). So, I would be for not using them.

So, I think we are ready to go public.

Best,
   Dan

**Pull request merged**
